kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis-for-canary
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis-for-canary
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: uniqueapp
          profile: opsmx-profile-v2
          user: admin
          lifetimeMinutes: "3"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: demoservice
            logTemplateName: "logtemp"
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: "oes-argo-rollout-{{args.baseline-hash}}.*" 
            canaryLogScope: "oes-argo-rollout-{{args.canary-hash}}.*"
