kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          profile: opsmx-profile-v3
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: final-tests
          user: admin
          baselineStartTime: "2022-09-30T04:11:00Z"
          canaryStartTime: "2022-09-30T04:11:00Z"
          lifetimeMinutes: "3"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: prometheusverification
          globalLogTemplate: logtemp
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*59f855cd9f.*"
            canaryLogScope: ".*757d8d979b.*"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,59f855cd9f,final-tests"
            canaryMetricScope: "argocd,757d8d979b,final-tests"
            metricTemplateName: "PrometheusMetricTemplate"
          - metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "argocd,59f855cd9f"
            canaryMetricScope: "argocd,757d8d979b"
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*59f855cd9f.*"
            canaryLogScope: ".*757d8d979b.*"
