apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net/
          user: admin
          application: newrelic1
          baselineStartTime: "2022-09-26T04:17:00.002Z"
          canaryStartTime: "2022-09-26T04:17:00.002Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: newreliccustom
            logScopeVariables: "app_key,pod_key"
            baselineLogScope: "issugen-baseline,6944b5c7df"
            canaryLogScope: "issugen-baseline,76f78f85ff"

