kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net
          application: analysisappoct6
          baselineStartTime: "2021-11-03T11:29:46.915Z"
          canaryStartTime: "2021-11-03T11:29:46.915Z"
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: elksvc1
            logTemplateName: oct6logtemp
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1"
