apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          profile: "opsmx-profile"
          gateUrl: https://oes-argoqa.isd-dev.opsmx.net/
          user: user2
          application: splunktest1
          baselineStartTime: "2022-03-08T10:46:00Z"
          canaryStartTime: "2022-03-08T10:46:00Z"
          lifetimeMinutes: 6
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: splunkint1
            logScopeVariables: " kubernetes.container_name"
            baselineLogScope: "oes-platform-br"
            canaryLogScope: "oes-platform-cr"

